### ISSUE TITLE
install failing; pymssql deprecated

### ISSUE THREAD

**Issue by WhiteAu** [FredHutch/sci-pkg#4]
`Collecting sci
  Using cached https://files.pythonhosted.org/packages/7c/6e/31e1db57af8feade7a621ad607842f843cec09a213b2c66071193a3ecd77/sci-0.1.5.tar.gz
Requirement already satisfied: requests in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from sci) (2.21.0)
Requirement already satisfied: python-hostlist in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from sci) (1.18)
Requirement already satisfied: psycopg2 in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from sci) (2.8.4)
Requirement already satisfied: PyMySQL in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from sci) (0.9.3)
Collecting pymssql
  Using cached https://files.pythonhosted.org/packages/4a/20/bcd4db9e7990b50e85280f0c9488c0a53f7e6bf9048203448d8e0f29a536/pymssql-3.0.3.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from requests->sci) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from requests->sci) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from requests->sci) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\whiteau\documents\github\nlp-airflow-dags\venv\lib\site-packages (from requests->sci) (2.8)
Building wheels for collected packages: pymssql
  Building wheel for pymssql (PEP 517): started
  Building wheel for pymssql (PEP 517): finished with status 'error'
  Running setup.py clean for pymssql
Failed to build pymssql

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\Scripts\python.exe' 'C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\whiteau\AppData\Local\Temp\tmpm95sg_3m'
       cwd: C:\Users\whiteau\AppData\Local\Temp\pycharm-packaging\pymssql
  Complete output (42 lines):
  C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\dist.py:46: DistDeprecationWarning: Do not call this function
    warnings.warn("Do not call this function", DistDeprecationWarning)
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install
  Traceback (most recent call last):
    File "C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\whiteau\Documents\GitHub\nlp-airflow-dags\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 182, in build_wheel
      metadata_directory)
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 493, in <module>
      tests_require=['pytest', 'unittest2'],
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\whiteau\AppData\Local\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\whiteau\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\whiteau\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\whiteau\AppData\Local\Temp\pip-build-env-1opvjlni\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "C:\Users\whiteau\AppData\Local\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\whiteau\AppData\Local\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 449, in run
      raise DeprecationWarning(msg)
  DeprecationWarning: The pymssql project has been discontinued.  To install the last working released version, use a
  version specifier like "pymssql<3.0".  For details and alternatives see:
  https://github.com/pymssql/pymssql/issues/668
  ----------------------------------------
  ERROR: Failed building wheel for pymssql
ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly`

**Comment by dtenenba** [comment]
I replaced pymssql with pyodbc and bumped the version of the package, which automatically creates a new version in PyPi. It should be fixed. Try again.

**Comment by WhiteAu** [comment]
Installing without issue in Python3 environment (PyCharm IDE)
Closing.
